### ISSUE TITLE
openssl lib generated ecdsa testvector, get >50% posibility verify failed.

### ISSUE THREAD

**Issue by LeonMac** [ZcashFoundation/zcash-fpga#17] opened 2020-05-25 02:59 UTC
Not sure where the problem would be, I generated multiple ecdsa test vectors, by using openssl library, there are 50% possibility the verification will be failed (and those testvector passed with the openssl verification process).

**Comment by bsdevlin** [comment] 2020-05-25 03:25
Can you paste some inputs where it failed? I can check as well.

**Comment by LeonMac** [comment] 2020-05-25 06:18
These are all generated by using openssl lib (verifed by openssl as well)

two failed TV:
==================================
0x 9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0  //Digest
0x 9e711857f82d6a35bc1131d43b6dc0d407400ddfdb61b17185a92cfe50cd826a  //sig.r
0x 1ba6cc471a01ecb58fa9f735365b194237336c680189e34a69bea49d56846b08  //sig.s
0x dbd91de72df28f89df4a6d4bef0103b4ceb69f4f3dc3299f48a0320262a3e00e  //pub.Qx
0x 22d72aa3f69e19fd1df3610cec165a79c96d31f1653d5638fa4b3ec900dee263  //pub.Qy

0x 9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0  //Digest
0x cc39c448031906fae471a042fca1316349c189ce909822558e79ba16dd7940bb  //sig.r
0x 02db5990ad93e2271ca8e628ede6390383ea44bb4da97377d2562aabf6d65c1f  //sig.s
0x 7609edcfc258cc2367ba9149d9f7d83adef82f636c729349ebac42fe009b2cf8  //pub.Qx
0x 83e93713b03e048feb6893eeb3cf367b410defc722e9f95c65612a03a9de9536  //pub.Qy
==================================
two passed TV
0x 9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0  //Digest
0x a088ef162244d69624e2ebc77c4723eee12cf36ec17c7596e8f968aac652cd23  //sig.r
0x bb350273b59ec76eeb19e81cf3bff31ae4d81a2329245da9750e10f90e2d5dff  //sig.s
0x 919dc4b7c7c4cfecc684705598720f117deb09a818548902b48fde148ad4afe2  //pub.Qx
0x b60ea888b8663b08d9f0dec052d33bfcc9efb58b8dff4ed273f7af2b3495fd9f  //pub.Qy

0x 9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0  //Digest
0x 099cd887a6499433ce7c22d0659df360668c8ef14b33b26863fb90bd70e669a9  //sig.r
0x f6155b5021dc8a12785fb7fc0634ae1fa6c10a0587b5be564d000937c0b59569  //sig.s
0x f7f39b36d4259ca20d6fc9c177ff11ef5a80af20ed955626c1fd714e1afa7ffc  //pub.Qx
0x 481b0408d42a2536ccd7f1637f2c3d034b4cf335f07d8e48cb31c71d00a3b2e1  //pub.Qy

**Comment by LeonMac** [comment] 2020-05-25 11:09
I upload the openssl tool to my git, it can be used for generate multiple TVs as you assigned. with the samilar format used in rtl code.
https://github.com/LeonMac/ecdsa-tv-gen.git

**Comment by bsdevlin** [comment] 2020-05-25 15:25
Can you post the secret key you used for the first failed test case?
I used this as my reference: https://www.cs.uaf.edu/2015/spring/cs463/lecture/03_25_signature/ECDSA.py 

But it says the points you pasted are invalid. So I want to try regenerating r/s from the key.

**Comment by LeonMac** [comment] 2020-05-26 04:03
I posted 4 TVs (two verified pass and two verified fail)--do you mean all of them are reported as invalid by the python script?
I don't record the secrete (do you mean private key?) for previous TVs. I had regerated few more with the private key print out as below, again I pick two passed, two failed.

//Two passed TV:
0e3d385206af06c88ca65794435b706e88ac4a01f8eaac08ca1af2210fe4dce2  //sig.r
289854a7723b90ea21414fe1eb527ff498e5df990ded6b7680da1869f6b7ebc1  //sig.s
5cccb2c135da09ee69a178aa9565863b1d7d028204a736506080a3eff4c8467a  //QX
dd54d88de2abf4d15cef60f79deeb48646977e5c0cb7a665c80f55c8f1b7ec11  //QY
===============================================
4276c027cd7ec78c0b26b8cb573c8538ebf45c374e3a328d4ad5633351f39ca1  //privkey

===============================================
f035f98f5b2a5f20a75e58056df900984ab4827aa2b987698127f073e1ad5fb1  //sig.r
cb505b81a5abb5f459042179d6acc7305de063cb3038b1928325b2116b9bf860  //sig.s
825c6d340e024135373dfa22ea2601207de7164ead447796ff079c99bfb59018  //QX
0f6233fd63320abdb963b82fd85c22292279d5f923e2d33f7c440fc10500a2b5  //QY
===============================================
134decf1992827a187671b70b1f2cfcb427baf0051a061af79c03c25b989dc57  //privkey
--------------------------------------------------------------------------
//Two failed TV
ae235401e2112948be75194de0bad0002e8e76e6cdf9267ccb179643d908dc5e  //sig.r
1f37bd6b617d03db5413cad3dc74fd091d071c2377fb74f488c56077823a2d56  //sig.s
5db9b06cc4928dd46f675c7dde14de8c7c2a8fd8e6c132da77e4ffeb90ff51d0  //QX
54d0967454193d20bc5733d0779ce3f6824666a3a9a66273c7f21e5f26ca0bbf  //QY
===============================================
8834bec0e3312c0e8a406e2d331292b354c5b976aa528e36d2607ddd186a56d3  //privkey

==============================
a0c388bad0d0de5b8cd74dde1b130ae24f727874e00b0a19c9a0ee336ea420cf  //sig.r
4d549363cea5e7cf2e5a80de97057e6709b8014c9037d12aac86b9ae4fbb02bb  //sig.s
87d4561f92925beb4afd97fb0f883bc1f7f573494087191af8bc67557b4ab0f9  //QX
0d933ed3e39c30e27dfde32f276ef50db3eef6cbea8e913f7488b3dff15fb3ee  //QY
===============================================
507c74cb3c1379adfeb585dc442058b900c7c08e2d78438864f99d7613a0b0c0  //privkey

**Comment by bsdevlin** [comment] 2020-05-26 22:53
Thanks - just confirming I can reproduce the error, I will work on a fix and let you know.

**Comment by bsdevlin** [comment] 2020-05-27 04:18
Actually I had an error in my own input, after I fixed it I have the testbench passing. Are you able to confirm these pass the secp256k1_top_tb.sv testbench? These were the two that failed for you.

test(3, 256'h9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0, //Digest
        256'hae235401e2112948be75194de0bad0002e8e76e6cdf9267ccb179643d908dc5e, //sig.r
        256'h1f37bd6b617d03db5413cad3dc74fd091d071c2377fb74f488c56077823a2d56, //sig.s
        256'h5db9b06cc4928dd46f675c7dde14de8c7c2a8fd8e6c132da77e4ffeb90ff51d0, //pub.Qx
        256'h54d0967454193d20bc5733d0779ce3f6824666a3a9a66273c7f21e5f26ca0bbf); //pub.Qy

test(4, 256'h9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0, //Digest
        256'ha0c388bad0d0de5b8cd74dde1b130ae24f727874e00b0a19c9a0ee336ea420cf, //sig.r
        256'h4d549363cea5e7cf2e5a80de97057e6709b8014c9037d12aac86b9ae4fbb02bb, //sig.s
        256'h87d4561f92925beb4afd97fb0f883bc1f7f573494087191af8bc67557b4ab0f9, //pub.Qx
        256'h0d933ed3e39c30e27dfde32f276ef50db3eef6cbea8e913f7488b3dff15fb3ee ); //pub.Qy

**Comment by LeonMac** [comment] 2020-05-27 07:33
Do you mean these two "failed TV" can passed by using secp256k1_top_tb.sv, without any change to current RTL code?
I am using a OpenCL based automation by calling the rtl kernel (which wrap up the ecdsa verify core of your project) to do test. If your secp256k1_top_tb test can pass by using these two TVs, I would suspect if there are problem of my wrapper.. just don't understand why some TVs still get pass..

**Comment by bsdevlin** [comment] 2020-05-27 12:30
Yeah I didn't change the RTL and they are passing. Let me also try on an
AWS F1 instance to make sure its not some bug there.

Is it always the same TV that fail for you? I mean if you just did a run
with one of these failing TV, it will always fail?

**Comment by LeonMac** [comment] 2020-05-28 01:42
Thanks a lot. However my problem does not happen on AWS, it is on my local development board based on Xilinx U200.
For my local test program ( RTL(ecdsa core + my wrapper to AXI) and a Host OpenCL to feed the TV to RTL package), automation test shows ~60%+ generated TV will be verified "fail". I had picked up few such "failed TV" and feed them to the RTL package for iteration test, fail rate is 100%. That looks good as this looks not some random issue..
Anyway if your test on top level ecdsa shows good then it looks most likely some proble exist in the data movement path (AXI, or my wrapper).

**Comment by lmaxeniro** [comment] 2020-06-29 03:22
Back to this issue report, a summary
1: The above two additional test vectors (let me named them as tv3/tv4), both pass in secp256k1_top_tb.sv.
2: They still fail in my local OpenCL test program--but the strange thing are: they can pass in HW emulation test, but fail in HW test.
3: so I back to the AWS for a comparing test: I hardcoded tv3 into test_zcash.cpp:
`      string_to_hex("9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0", (unsigned char *)verify_secp256k1_sig.hash);
      string_to_hex("ae235401e2112948be75194de0bad0002e8e76e6cdf9267ccb179643d908dc5e", (unsigned char *)verify_secp256k1_sig.r);
      string_to_hex("1f37bd6b617d03db5413cad3dc74fd091d071c2377fb74f488c56077823a2d56", (unsigned char *)verify_secp256k1_sig.s);
      string_to_hex("5db9b06cc4928dd46f675c7dde14de8c7c2a8fd8e6c132da77e4ffeb90ff51d0", (unsigned char *)verify_secp256k1_sig.Qx);
      string_to_hex("54d0967454193d20bc5733d0779ce3f6824666a3a9a66273c7f21e5f26ca0bbf", (unsigned char *)verify_secp256k1_sig.Qy);
`
Then test on AWS fpga, here is the log (**.bm = 0x8**, means verify failed)
`INFO: AFI PCI  Vendor ID: 0x1d0f, Device ID 0xf000
INFO: Read 0x280000 from ISR register.
WARNING: Expected 0x01D00000.
INFO: Read 0x1fc from TDFV register.
INFO: Read 0x0 from RDFO register.
INFO: AXI4 mode is set DISABLED
INFO: write_stream::Wrote 8 bytes of data
INFO: Read FIFO shows 40 bytes waiting to be read from FPGA
INFO: Read 40 bytes from read_stream()
INFO: FPGA version: 0x10402, built on 0x6c6444617465227d
INFO: FPGA capability register: 0xd [ENB_VERIFY_EQUIHASH_200_9: 1, ENB_VERIFY_EQUIHASH_144_5 0, ENB_VERIFY_SECP256K1_SIG 1, ENB_BLS12_381 1]
INFO: Finished initializing FPGA.
INFO: Testing secp256k1 core...
INFO: write_stream::Wrote 176 bytes of data
INFO: Read FIFO shows 24 bytes waiting to be read from FPGA
INFO: Read 24 bytes from read_stream()
INFO: verify_secp256k1_sig_rpl.hdr.cmd = 0x80000101
INFO: verify_secp256k1_sig_rpl.bm = 0x8
INFO: verify_secp256k1_sig_rpl.index = 0xa
INFO: verify_secp256k1_sig_rpl.cycle_cnt = 0x2e47
ERROR: Signature verification failed!
`
I also tried the tv4, it also failed **.bm = 0x8**
`INFO: Testing secp256k1 core...
INFO: write_stream::Wrote 176 bytes of data
INFO: Read FIFO shows 24 bytes waiting to be read from FPGA
INFO: Read 24 bytes from read_stream()
INFO: verify_secp256k1_sig_rpl.hdr.cmd = 0x80000101
INFO: verify_secp256k1_sig_rpl.bm = 0x8
INFO: verify_secp256k1_sig_rpl.index = 0xa
INFO: verify_secp256k1_sig_rpl.cycle_cnt = 0x2e43
ERROR: Signature verification failed!
`

**Comment by LeonMac** [comment] 2020-06-29 11:13
Back to this issue report, a summary
1: The above two additional test vectors (let me named them as tv3/tv4), both pass in secp256k1_top_tb.sv.
2: They still fail in my local OpenCL test program--but the strange thing are: they can pass in HW emulation test, but fail in HW test.
3: so I back to the AWS for a comparing test: I hardcoded tv3 into test_zcash.cpp:
string_to_hex("9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0", (unsigned char *)verify_secp256k1_sig.hash); string_to_hex("ae235401e2112948be75194de0bad0002e8e76e6cdf9267ccb179643d908dc5e", (unsigned char *)verify_secp256k1_sig.r); string_to_hex("1f37bd6b617d03db5413cad3dc74fd091d071c2377fb74f488c56077823a2d56", (unsigned char *)verify_secp256k1_sig.s); string_to_hex("5db9b06cc4928dd46f675c7dde14de8c7c2a8fd8e6c132da77e4ffeb90ff51d0", (unsigned char *)verify_secp256k1_sig.Qx); string_to_hex("54d0967454193d20bc5733d0779ce3f6824666a3a9a66273c7f21e5f26ca0bbf", (unsigned char *)verify_secp256k1_sig.Qy);
Then test on AWS fpga, here is the log (.bm = 0x8, means verify failed)
INFO: AFI PCI Vendor ID: 0x1d0f, Device ID 0xf000 INFO: Read 0x280000 from ISR register. WARNING: Expected 0x01D00000. INFO: Read 0x1fc from TDFV register. INFO: Read 0x0 from RDFO register. INFO: AXI4 mode is set DISABLED INFO: write_stream::Wrote 8 bytes of data INFO: Read FIFO shows 40 bytes waiting to be read from FPGA INFO: Read 40 bytes from read_stream() INFO: FPGA version: 0x10402, built on 0x6c6444617465227d INFO: FPGA capability register: 0xd [ENB_VERIFY_EQUIHASH_200_9: 1, ENB_VERIFY_EQUIHASH_144_5 0, ENB_VERIFY_SECP256K1_SIG 1, ENB_BLS12_381 1] INFO: Finished initializing FPGA. INFO: Testing secp256k1 core... INFO: write_stream::Wrote 176 bytes of data INFO: Read FIFO shows 24 bytes waiting to be read from FPGA INFO: Read 24 bytes from read_stream() INFO: verify_secp256k1_sig_rpl.hdr.cmd = 0x80000101 INFO: verify_secp256k1_sig_rpl.bm = 0x8 INFO: verify_secp256k1_sig_rpl.index = 0xa INFO: verify_secp256k1_sig_rpl.cycle_cnt = 0x2e47 ERROR: Signature verification failed!
I also tried the tv4, it also failed .bm = 0x8
INFO: Testing secp256k1 core... INFO: write_stream::Wrote 176 bytes of data INFO: Read FIFO shows 24 bytes waiting to be read from FPGA INFO: Read 24 bytes from read_stream() INFO: verify_secp256k1_sig_rpl.hdr.cmd = 0x80000101 INFO: verify_secp256k1_sig_rpl.bm = 0x8 INFO: verify_secp256k1_sig_rpl.index = 0xa INFO: verify_secp256k1_sig_rpl.cycle_cnt = 0x2e43 ERROR: Signature verification failed!

1. checked with the test code, bm=0x8 looks not a defined status?
typedef enum : uint8_t {
      TIMEOUT_FAIL     = 0,
      FAILED_SIG_VER   = 1,
      X_INFINITY_POINT = 2,
      OUT_OF_RANGE_S   = 3,
      OUT_OF_RANGE_R   = 4
    } secp256k1_ver_t;

2. Also I had tried some ugly thing to input totally invalid test vector (for Exp, all "0" except only few bytes)-- this will completely kill the fpga, that I have to reset fpga to recover it.

**Comment by LeonMac** [comment] 2020-07-01 06:11
I make a test code to reproduce the issue--please check my merge request.

**Comment by bsdevlin** [comment] 2020-07-02 01:26
Thanks - let me debug your test cases a little (it is a holiday weekend so it might not be until next week) and let you know what I find.
For your questions:
#1 0x8 should be OUT_OF_RANGE_S since I think it is encoded one hot (multiple bits can fail).
#2 Im not surprised some version of the input will make it hang - since it does inversions and if the input is invalid it might get stuck trying to find the modulo inverse which doesn't exist.

**Comment by LeonMac** [comment] 2020-07-03 01:56
#1 So OUT_OF_RANGE_S = 3 is the bit wise (0h1000?) correct? 
#2 SW solution handle that better, I am not sure if that will be difficult to add some protection? (to avoid making hw out-of-work)

**Comment by LeonMac** [comment] 2020-07-14 03:07
@bsdevlin is there any progress? please let me know if I can help to do something...I also made a openssl dynamic generate test vector tool which can be used to automatically generat test vector to feed into foga for testing. check my pull request.

**Comment by bsdevlin** [comment] 2020-08-08 15:39
I just pushed an update that fixes the test5 locking up, it locks because there is no inverse for the S value, there should of been a timeout to protect from this lockup but it had a bug. Have a look at what I pushed. 

I am doing a build in AWS now to see if I can reproduce your issue of openssl inputs failing.

**Comment by LeonMac** [comment] 2020-08-11 02:45
@bsdevlin Yes it looks for tv5, the fpga lock-up is gone, and the readback is as below (these are tested on my local machine): The report (bm) is 0x10=10000--is that the OUT_OF_RANGE_R error? (is this align to your expectation)? 
`.hdr.cmd   = 0x80000101
.hdr.len   = 0x00000013
.index	 = 0x00000001
.report    = 0x10
.cycle_cnt = 0xffff`

Sorry on my AWS F1 machine the Vivado license is expried so I can not build new fpga image for verify at present (I am asking for AWS help but will need some time). 
Did you get progress on the tv3/tv4 verify fail (and move forward, any dynamic openssl generated tv..).

**Comment by bsdevlin** [comment] 2020-08-11 23:43
Yes it should be 0x10 (TIMEOUT_FAIL), the bitmask maps to the code here:
https://github.com/ZcashFoundation/zcash-fpga/blob/master/zcash_fpga/src/rtl/secp256k1/secp256k1_pkg.sv#L78-L85

For tv3/4/openssl I had a problem that the image I built in AWS doesn't work (the basic test won't work) and I need to do some debug as to why (it might be due to AWS shell changes).

**Comment by LeonMac** [comment] 2020-08-12 01:59
From this bitmask, 0x08 (0b1000) is the TIMEOUT_FAIL, 0x10(0b10000) is the FAILED_SIG_VER. Is that the correct understnding?

typedef struct packed {
    logic [2:0] padding;
    logic TIMEOUT_FAIL;
    logic FAILED_SIG_VER;
    logic X_INFINITY_POINT;
    logic OUT_OF_RANGE_S;
    logic OUT_OF_RANGE_R;
  } secp256k1_ver_t;

I had updated the test code follow your review comments feedback--That I suppose can be used for verifying the batch of signatures automaticlly rather by hardcoded--however tv3/tv4 can be checked firstly.
If you have confidence to the update, you can also share that to me so I can verify on my local FPGA. The AWS F1 is good thing but it is just hardly to be used, that is why it is not very sucessful.

**Comment by bsdevlin** [comment] 2020-08-12 02:35
I wrote the bitmask below:

typedef struct packed {
logic [2:0] padding;
logic TIMEOUT_FAIL;                [0x10]
logic FAILED_SIG_VER;            [0x8]
logic X_INFINITY_POINT;          [0x4]
logic OUT_OF_RANGE_S;        [0x2]
logic OUT_OF_RANGE_R;        [0x1]
} secp256k1_ver_t;

I don't have a fix yet for tv3/4, I want to reproduce the problem first,
hopefully I'll know this week.

**Comment by bsdevlin** [comment] 2020-08-16 16:43
Just an update - I can reproduce the tv3/tv4 failing on AWS FPGA (but not in simulation), so I am debugging it by adding ILA cores to try see what stage goes wrong. So slowly making progress.

**Comment by LeonMac** [comment] 2020-08-17 04:43
Yes that is same as what I had obeserved--the test can be passed in the FPGA testbech based test, also passed in the FPGA HW Emulation test, but will be failed on the actual HW test.
Thanks a lot for the update and the debug effort.

**Comment by bsdevlin** [comment] 2020-08-20 16:12
I just pushed a fix for the tv3/4 issue, I haven't tried running it on a large number of vectors yet. Issue looks like it might be a bug in Vivado and a difference in how simulation vs actual implementation uses local parameters. Let me know if this fixes it.

**Comment by LeonMac** [comment] 2020-08-21 07:08
@bsdevlin There is only one rtl design change, correct? that is "barret_mod.sv"

I just build out an HW image on my local FPGA machine, but test result still failed on tv3/tv4 (and pass on tv1/tv2).
I am not sure if you have done the test by using the test program I pushed on AWS? I still can not compile on AWS due to license issue so not able to check that on AWS...

**Comment by LeonMac** [comment] 2020-08-24 05:06
@bsdevlin I think the /zcash_fpga.cpp#L97-L99 does not impact my local FPGA test.
I did some test and I am confused now...Maybe I miss something or miss-understand something?

1. I reviewed the code context -- in the openssl tv gen code, I use the plain message "I am a fish" which is what you used for tv1 (I get the exact same digest "4c7dbc...e67fd4" as tv1), so if I flip that before sending to fpga then the tv1/tv2 verify should be failed.. 

2. Without update of the barret_mod.sv and the digest flip, I get 100% verify fail for the openssl dynamic test; but after update these two changed, I am now get some dynamic TV verified passed, but still some fail--overall the pass rate is somewhat less than 50% (not the fix number)-- but you mentioned you can pass 1000 round test, can you confirm that?

**Comment by LeonMac** [comment] 2020-08-24 05:11
I paste two more failed TV (which are captured from my dynamic tv-gen test and confimed failed in hardcoding test)--if can you help to do a quick verify on your side?

-------------------------------- //TV5
4c7dbc46486ad9569442d69b558db99a2612c4f003e6631b593942f531e67fd4  //digest
f7df023855dab4adda1b410214f832fc1fb4368c376e236e3a23ff19f42749a8  //sig.r
79e9938d65a3f7a81e15b18b898a822a03ad152f2b763df8d903ea1190fb51ae  //sig.s
7af8bcbcf63d0faff8b52ec5084281f02612be3eb43b2157d64b6f61cbde3a9b  //QX
30027bf9888d97bfc8816e3ec5fca6063caa895b0fb034e65a38acf135f22eae  //QY
--------------------------------------------------
54659a59a82cb3b6edf7aebbb058c51b51b8a1902d2ebd30d4554bf8d537df28  //PRIV
--------------------------------------------------

-------------------------------- //TV6
4c7dbc46486ad9569442d69b558db99a2612c4f003e6631b593942f531e67fd4  //digest
485a1e712c381f57c6d8012a6eb8e1f63b1723fdf08632b4b868eb9a600c2d5c  //sig.r
360cd42c47e498c347961c2ba73b5609833da0570dcf40cea567ba22b97a6d04  //sig.s
fd16f2f5d720e9d0a7208e11d256f1d70cdfe1bf1730445601a3ca49afbff5ca  //QX
0d64c5bf411d9a10e060526956b21d72f24ec81800ed53c598fbcb2a31dd7945  //QY
--------------------------------------------------
3784e7bfb427028a6e2fbb9260c09a6db8c3f9a209c4f1fb0b0dee77a55cc696  //PRIV
--------------------------------------------------

**Comment by bsdevlin** [comment] 2020-08-24 22:36
1. I'm not too sure - I did a dump of what your program was sending the FPGA compared to what it should be, and it was flipped, so I had to swap the digest to get it to match.

2. I tested the two new cases and they passed for me - but I realized I had disabled endomorph in my build, so I did another build based from master and it failed - so I'll try find out what's happening.

**Comment by LeonMac** [comment] 2020-08-25 02:16
1 my previous judgement probably is wrong--it might be due to the memory map different between the "hardcoded TV" and a "openssl generated TV", I will double check;
2, do you mean you can pass the two case (tv3/tv4) with the setup [USE_ENDOMORPH = "NO"]?  And with [USE_ENDOMORPH = "YES"] you 
My build is using  [USE_ENDOMORPH = "NO"] right now actually... anyway I will clear up and redo the build to confirm.

**Comment by bsdevlin** [comment] 2020-08-25 02:23
Actually I was passing all test cases, but I had a couple of small changes I thought were unrelated - but after I went back to master I see the failures again, so it might be something else as well. I am going to try do a build to figure it out, I might be offline for the next week but will let you know if I find something.

**Comment by bsdevlin** [comment] 2020-09-06 22:52
Can you try again? Test cases are all passing for me with this update.

The bug seems to something when Vivado implements the barret mod and the result is greater than the modulus - so it should subtract (takes one clock), in simulation this works, but when using ILAs the module just ignores this step and outputs a 0 result which causes the calculation to fail. I think it is related to bit widths not being the same and so the comparison operation is implemented in hardware differently to simulation.

**Comment by LeonMac** [comment] 2020-09-07 05:43
OK, I am still having issue for my local FPGA test, nothing improved--this is really strange.
I will launch up a new AWS devlopment instance to build and try.
BTW, you had passed all the test on both your local FPGA and AWS I assume? what Vivado sythesizer version are you using?

**Comment by bsdevlin** [comment] 2020-09-07 13:38
I only tested on AWS - I made the AFI public in case you want to try testing it (region us-east-1)
{
    "FpgaImageId": "afi-02042853277b16f7e",
    "FpgaImageGlobalId": "agfi-0a6755ae3328716c7"
}

I had some debugging things in the image so I will revert back to master and make a new build to confirm.

**Comment by LeonMac** [comment] 2020-09-08 04:43
I can not access this afi--this is due to aws's restrction--so I had build myself image last night (not include your most recent git commit).
I then use the two test program to try--to my suprise --they are failed (tv1/tv2 pass, tv3/tv4 fail, dynamic tv >50% fail)--this is align to my local test result.
Please let me know your recent result on AWS (100% align on the code of the master branch?) I need to sync. on your page..

**Comment by bsdevlin** [comment] 2020-09-09 12:18
So I did a build from master, and it failed, and then I only added ILA and did a re-build, and it works.

The only thing I can think that would do this would be the clock crossing in zcash_fpga_top.sv, so I am going to try replacing the FIFO with a standard Xilinx one and let you know if that provides reliable results. If you are able to try that too (remove the clock crossing or use a standard Xilinx FIFO) it would be good to try,

**Comment by LeonMac** [comment] 2020-09-10 02:22
@bsdevlin good to know that, now at least I am on the same page with you.. if you have a ILA added version (maybe make a debug branch other than master branch) that I can build and try?
regarding your concerning on clock-crossing , sorry I do not have enough knowledge and to do that, so have to rely on you.. 
BTW regarding the FIFO I am not sure if you mean the 32b/64b AXI bus convert -- just FYI for my local FPGA design I use a Xilinx 32/64 convert IP but not your lib and still have the issue--so if you doubt that 32b/64b AXI bus convert, I think you can put that to the sencond priority..

**Comment by bsdevlin** [comment] 2020-09-10 17:58
I did a build form master with the latest changes (FIFO and some control logic bug I found) and it is passing all the tests for me, can you give that one a try?

**Comment by LeonMac** [comment] 2020-09-11 02:11
Sure I will build that on AWS to test firstly--if you had already pass that on AWS (with the exactly same master branch), I think I shall be OK as well.
Just exmine this commit update -- all design files updated which I have been using in my local fpga application is zcash_fpga_pkg.sv, that file just got 1 line change (enable the ENB_VERIFY_SECP256K1_SIG = 1). so I assume your update will not solve my local fpga problem even on the AWS it works fine. 
also it look you add another level top control "control_top.sv" --is that a vital change (to adopt the "new FIFO")?

**Comment by bsdevlin** [comment] 2020-09-11 03:19
I'm not too sure if the latest updates with the FIFO will help you, if you have a github of the code version you are running I can have a look.

**Comment by LeonMac** [comment] 2020-09-11 10:14
I just have one aws build out on--but the result is still....fail... 
I need to double check, maybe starting from scratch to redo full project git clone and rebuild.. as AWS build also rely on aws-fpga platform setup--can you let me know what specific aws-fpga branch you are using?  
Also for local build there are make clean script--I don't know if you have aws version make clean script or I can simply delete some documents?

**Comment by bsdevlin** [comment] 2020-09-12 01:05
I was running 1.4.15. I just checked out new folders and started from scratch for both aws and zcash repos.

**Comment by LeonMac** [comment] 2020-09-14 07:41
@bsdevlin I git clone the aws-fpga 1.4.15, and the zcash-fpga master project, then rebuild the project on aws machine, but I am still fail..
Only one change I made due to one script error report during the build (cl_common_defines.vh can not be found) therefore I changed the contents of the  https://github.com/ZcashFoundation/zcash-fpga/blob/master/aws/cl_zcash/build/scripts/encrypt.tcl#Line63 from

`file copy -force $CL_DIR/../common/design/cl_common_defines.vh        $TARGET_DIR `
to 
`file copy -force $CL_DIR/../../examples/common/design/cl_common_defines.vh        $TARGET_DIR`

I am really out of mind now...I wonder if it is possible for you to share your build out "tar file of dcp" to smoehwere --so I can download that and then create my local fpga afi then to run a cpp test??

**Comment by bsdevlin** [comment] 2020-09-24 00:10
Closing this as it is fixed for me

**Closed by bsdevlin** 2020-09-24 00:10 UTC
